# Generated by Django 4.2.2 on 2023-06-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tag_created_at_tag_updated_at_alter_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
